### ISSUE TITLE
Wrong ADC DMA initialization

### ISSUE THREAD

**Issue by PolishHammer** [kamilwil/PMIK-tuner#1]
https://github.com/kamilwil/PMIK-tuner/blob/2839b2ac599087f3646df1fa530553a9ceaf1530/Src/main.c#L113

Is:
- `HAL_ADC_Start_DMA(&hadc2, (uint32_t*)value, 1)`

Should be one of this:

- `HAL_ADC_Start_DMA(&hadc2, (uint32_t*)&value, 1)`
or
- `HAL_ADC_Start_DMA(&hadc2, &value, 1)`

**Comment by kamilwil** [comment]
Fixed via 9630bc453689a7820c7aebfb50b770cd45291289

Thanks once again :)
